<?php

	$style = array(
					'font' => 'font-family: Helvetica Neue, Helvetica, Helvetica, Arial, sans-serif;font-size: 15px;line-height: 1.5em;margin: 0;padding: 0;',
					'img' => 'max-width: 300px; width: auto;',
					'body' => '-webkit-font-smoothing: antialiased;height: 100%; -webkit-text-size-adjust: none; width: 100% !important;',
					'a' => 'color:{primary_color};',
					'btn_primary' => 'margin-bottom: 10px;width: 100% !important;',
					'btn_primary_td' => 'background-color: {primary_color}; border-radius: 5px; font-size: 14px; text-align: center;vertical-align: top;',
					'btn_primary_td_a' => 'background-color: {primary_color};border: solid 1px {primary_color};border-radius: 5px;border-width: 10px 20px;display: inline-block;color: #ffffff;cursor: pointer;font-weight: bold;line-height: 2;text-decoration: none;font-size: 16px;',
					'text_content' => 'margin-bottom:15px;margin-top: 15px;',
					'justify' => 'margin-bottom:15px;',
					'primary_color' => 'color:{primary_color};',
					'secondary_color' => 'color:{secondary_color};',
					'h1_title' => 'border-bottom: 3px solid {secondary_color};font-weight: bold;margin-top: 0px; font-size: 28px;',
					'rrss_li_i' => 'font-size:16px;color:{primary_color}',
					'rrss_li' => 'float:left;list-style:none;',
					'body' => '-webkit-font-smoothing: antialiased;height: 100%;-webkit-text-size-adjust: none;width: 100% !important;',
					'body_wrap_container' => 'padding: 20px;',
					'container' => 'clear: both !important;display: block !important;margin: 0 auto !important;max-width: 600px !important;',
					'header_wrap' => 'margin-top:20px;clear: both !important;width: 100%;',
					'content' => 'display: block;margin: 0 auto;max-width: 600px;',
					'content_table' => 'width: 100%;',
					'center' => '',
					'hr' => 'height: 1px;border: 0;color: {secondary_color};background-color: {secondary_color};',
					'table_footer_wrap' => 'clear: both !important;width: 100%;',
					'footer_wrap_container_p' => 'color: #ababab;font-size: 12px;',
					'table_footer_wrap_a' => 'color: #999999;',
					'table_body_wrap' => 'padding: 0 20px 20px; width: 100%;',
					'table_body_wrap_container' => 'border: 1px solid #f0f0f0; width: 600px;',
					'ul_lo_li' => 'margin-left: 5px;list-style-position: inside;',
					'ul_lo_p' => 'font-size: 14px;font-weight: normal;margin-bottom: 10px;',
					'social' => 'height: 40px; display:block; position:relative; margin:0px 5px; padding:0px; top:0px; ',
					'facebook' => "left:0px; width:40px; float:left; background:url('".base_url('assets/assets_public/images/iconos-sociales.png')."') 0 0;",
					'googleplus' => "left:0px; width:40px; float:left; background:url('".base_url('assets/assets_public/images/iconos-sociales.png')."') 320px;",
					'linkedin' => "left:0px; width:40px; float:left; background:url('".base_url('assets/assets_public/images/iconos-sociales.png')."') 280px;",
					'twitter' => "left:0px; width:40px; float:left; background:url('".base_url('assets/assets_public/images/iconos-sociales.png')."') 120px;",
					'youtube' => "left:0px; width:40px; float:left; background:url('".base_url('assets/assets_public/images/iconos-sociales.png')."') 480px;",
					'contact' => 'color: {secondary_color}; margin-top:5px;',
					'contact_phone' => 'color:{primary_color}; font-size:25px; font-weight:bold;',
					'contact_title' => 'color:{primary_color}; margin-bottom:0;',
				);

?>
