<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customers extends \Entities\Customers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Customers' . "\0" . 'id', '' . "\0" . 'Entities\\Customers' . "\0" . 'provinceId', '' . "\0" . 'Entities\\Customers' . "\0" . 'name', '' . "\0" . 'Entities\\Customers' . "\0" . 'surname', '' . "\0" . 'Entities\\Customers' . "\0" . 'nif', '' . "\0" . 'Entities\\Customers' . "\0" . 'phonePrimary', '' . "\0" . 'Entities\\Customers' . "\0" . 'phoneSecond', '' . "\0" . 'Entities\\Customers' . "\0" . 'email', '' . "\0" . 'Entities\\Customers' . "\0" . 'address', '' . "\0" . 'Entities\\Customers' . "\0" . 'zip', '' . "\0" . 'Entities\\Customers' . "\0" . 'dischargeDate', '' . "\0" . 'Entities\\Customers' . "\0" . 'dischargeDateCode', '' . "\0" . 'Entities\\Customers' . "\0" . 'upDate', '' . "\0" . 'Entities\\Customers' . "\0" . 'state', '' . "\0" . 'Entities\\Customers' . "\0" . 'entranceRegister'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Customers' . "\0" . 'id', '' . "\0" . 'Entities\\Customers' . "\0" . 'provinceId', '' . "\0" . 'Entities\\Customers' . "\0" . 'name', '' . "\0" . 'Entities\\Customers' . "\0" . 'surname', '' . "\0" . 'Entities\\Customers' . "\0" . 'nif', '' . "\0" . 'Entities\\Customers' . "\0" . 'phonePrimary', '' . "\0" . 'Entities\\Customers' . "\0" . 'phoneSecond', '' . "\0" . 'Entities\\Customers' . "\0" . 'email', '' . "\0" . 'Entities\\Customers' . "\0" . 'address', '' . "\0" . 'Entities\\Customers' . "\0" . 'zip', '' . "\0" . 'Entities\\Customers' . "\0" . 'dischargeDate', '' . "\0" . 'Entities\\Customers' . "\0" . 'dischargeDateCode', '' . "\0" . 'Entities\\Customers' . "\0" . 'upDate', '' . "\0" . 'Entities\\Customers' . "\0" . 'state', '' . "\0" . 'Entities\\Customers' . "\0" . 'entranceRegister'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Customers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvinceId($provinceId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvinceId', [$provinceId]);

        return parent::setProvinceId($provinceId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvinceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvinceId', []);

        return parent::getProvinceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurname($surname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurname', [$surname]);

        return parent::setSurname($surname);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurname', []);

        return parent::getSurname();
    }

    /**
     * {@inheritDoc}
     */
    public function setNif($nif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNif', [$nif]);

        return parent::setNif($nif);
    }

    /**
     * {@inheritDoc}
     */
    public function getNif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNif', []);

        return parent::getNif();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhonePrimary($phonePrimary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhonePrimary', [$phonePrimary]);

        return parent::setPhonePrimary($phonePrimary);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhonePrimary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhonePrimary', []);

        return parent::getPhonePrimary();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneSecond($phoneSecond)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneSecond', [$phoneSecond]);

        return parent::setPhoneSecond($phoneSecond);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneSecond()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneSecond', []);

        return parent::getPhoneSecond();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setZip($zip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZip', [$zip]);

        return parent::setZip($zip);
    }

    /**
     * {@inheritDoc}
     */
    public function getZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZip', []);

        return parent::getZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setDischargeDate($dischargeDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDischargeDate', [$dischargeDate]);

        return parent::setDischargeDate($dischargeDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDischargeDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDischargeDate', []);

        return parent::getDischargeDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDischargeDateCode($dischargeDateCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDischargeDateCode', [$dischargeDateCode]);

        return parent::setDischargeDateCode($dischargeDateCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDischargeDateCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDischargeDateCode', []);

        return parent::getDischargeDateCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpDate($upDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpDate', [$upDate]);

        return parent::setUpDate($upDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpDate', []);

        return parent::getUpDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntranceRegister($entranceRegister)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntranceRegister', [$entranceRegister]);

        return parent::setEntranceRegister($entranceRegister);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntranceRegister()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntranceRegister', []);

        return parent::getEntranceRegister();
    }

}
